#!/bin/sh
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/dotfiles/.bashrc ~/.bashrc
ln -sf ~/dotfiles/.git-completion.bash ~/.git-completion.bash
ln -sf ~/dotfiles/.pureline.conf ~/.pureline.conf
